[ko]
  languageName = "Korean"
  contentDir = "content"
  weight = 15
  [ko.params]
    languageISO = "KR"
    languageTag = "ko-KR"
    footer = '<a class="text-muted" href="https://talosftc.com/">Team TALOS</a>'
    alertText = 'Alert'